name: 'Create GitHub Release'
description: 'Create a new GitHub release in your CI workflows'
inputs:
  draft:
    description: 'Create releases as a draft so they need to be manually published'
    required: false
    default: 'true'
  files:
    description: 'Release artifact file paths separated by new lines'
    required: false
  git-tag:
    description: 'Git tag name'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
