name: publish
on:
  push:
    tags: [v*.*.*]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: bun run lint
      - run: bun run test
      - name: Check no untracked changes
        run: |
          git_status=$(git status --porcelain)
          test -z "$git_status" || exit 1
          echo "$git_status"
      - uses: ./
        with:
          git-tag: ${{ github.ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
